name: Pierwszy workflow

on:
  push:
    branches: [ "umwc-lab1" ]
  pull_request:
    branches: [ "umwc-lab1" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: WyÅ›wietl zawartoÅ›Ä‡ katalogu
        run: ls -la

      - name: WyÅ›wietl wiadomoÅ›Ä‡
        run: echo "Gratulacje! TwÃ³j pierwszy workflow dziaÅ‚a! ğŸ‰"
